repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-xml
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/grigoriev/pre-commit-check-git-user
    rev: v0.9.0
    hooks:
      - id: check-git-config-user-email
        args: [ '--templates', '^\S+\.\S+@sbb\.ch$' ]
